title: Intro to Religious Studies, Fall 2018
description: > # this means to ignore newlines until "baseurl:"
  This is the course webpage for Intro to Religious Studies at Lawrence University
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rlst100.party" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Intro to Religious Studies, Fall 2018
author-img: mainhall.jpg
about-author: This is the webpage for Professor Kassor's RLST 100 course (Fall '18). Here is where you'll find readings, documents, and all information relevant to the course. If you want to find Prof. Kassor outside of class, she's in Main Hall 411, and her office hours are Mondays 3:30-4:30pm, and by appointment.
email: constance.e.kassor@lawrence.edu

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 12
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
